orbs:
  docker: circleci/docker@0.5.2
version: 2.1
workflows:
  build-and-publish-docker-image:
    jobs:
      - docker/publish:
          context: mycontext
          dockerfile: Dockerfile
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          path: SampleApplication/SampleApplication
          registry: hub.docker.com
