orbs:
  docker: circleci/docker@0.5.2
version: 2.1
workflows:
  build-and-publish-docker-image:
    jobs:
      - docker/publish:
          context: mycontext
          dockerfile: SampleApplication/SampleApplication/Dockerfile
          registry: index.docker.io
          image: nachiappan/testapplication

