version: 2.1

orbs:
  docker: circleci/docker@0.5.2

jobs:
  build-and-push:
    machine: true
    steps:
      - checkout
      - run: pwd
      - run: echo "The above is pwd"
      - run: ls
      - run: echo "The above is ls"
      - docker/build:
          path: SampleApplication
          image: nachiappan/testapplication
          dockerfile: SampleApplication/SampleApplication/Dockerfile
      - docker/push:
          image: nachiappan/testapplication
          registry: index.docker.io
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"

workflows:
  my-workflow:
    jobs:
      - build-and-push:
          context: mycontext


