jobs:
  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: nachiappan/testapplication
          path: SampleApplication
          dockerfile: SampleApplication/Dockerfile
      - docker/push:
          digest-path: /tmp/digest.txt
          image: nachiappan/testapplication
          registry: index.docker.io
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
orbs:
  docker: circleci/docker@0.5.2
version: 2.1
workflows:
    jobs:
      - build-and-push

