version: 2.1

orbs:
  docker: circleci/docker@0.5.2

jobs:
  docker-build-push:
    machine: true
    steps:
      - checkout
      - docker/check:
          registry: docker.io
      - docker/build:
          path: SampleApplication
          image: nachiappan/testapplication
          dockerfile: SampleApplication/SampleApplication/Dockerfile
          tag: attempt
      - docker/push:
          image: nachiappan/testapplication
          registry: docker.io
          tag: attempt

workflows:
  dockerized-application:
    jobs:
      - docker-build-push:
          context: mycontext


