version: 2.1

orbs:
  docker: circleci/docker@0.5.2

jobs:
  docker-build-push:
    machine: true
    steps:
      - checkout
      - docker/check:
          registry: docker.io
      - docker/build:
          path: SampleApplication
          image: nachiappan/testapplication
          dockerfile: SampleApplication/SampleApplication/Dockerfile
          tag: attempt
      - run:
          name: compute-tag
          command: |
            branchName=${CIRCLE_BRANCH:0:20}
            commitNumber=$(git rev-list --count HEAD)
            MYTAG=${branchName}"-"${commitNumber}"-"${CIRCLE_SHA1}
            echo "$MYTAG"
      - run:
          name: print-tag
          command: |
            echo "$MYTAG"
      - docker/push:
          image: nachiappan/testapplication
          registry: docker.io
          tag: attempt

workflows:
  dockerized-application:
    jobs:
      - docker-build-push:
          context: mycontext


