version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: The First Step
          command: |
            ls
            docker build SampleApplication -f SampleApplication/SampleApplication/Dockerfile
            echo 'This is the delivery pipeline'
