version: 2.1

orbs:
  docker: circleci/docker@0.5.2

jobs:
  build-and-push:
    docker:
      - image: circleci/golang:1.13-alpine
    steps:
      - setup_remote_docker
      - checkout
      - docker/build:
          image: nachiappan/testapplication
          path: SampleApplication
          dockerfile: SampleApplication/Dockerfile
      - docker/push:
          image: nachiappan/testapplication
          registry: index.docker.io
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"

workflows:
  my-workflow:
    jobs:
      - build-and-push:
          context: mycontext


