jobs:
  build-and-push:
    executor: docker/docker
    context: mycontext
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: nachiappan/testapplication
          path: SampleApplication
          dockerfile: SampleApplication/Dockerfile
      - docker/push:
          image: nachiappan/testapplication
          registry: index.docker.io
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
orbs:
  docker: circleci/docker@0.5.2
workflows:
  version: 2
  my-workflow:
    jobs:
      - build-and-push

