version: 2.1
jobs:
  build:
    docker:
      - image: alpine:3.7
    working_directory: ~/SampleApplication
    steps:
      - checkout
      - run:
          name: The First Step
          command: |
            docker build . -f ./SampleApplication/Dockerfile
            echo 'This is the delivery pipeline'
